name: Lint PR
on: 
    pull_request:
        types: [opened, reopened, synchronize]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v4
              with:
                python-version: '3.9' 
            - uses: chartboost/ruff-action@v1
              with:
                args: check --fix .
            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                commit_message: 'style fixes by ruff'                        
