name: Auto packing
on:
    release:
        types:
            - published
jobs:
    auto_packing:
        runs-on: ubuntu-latest
        permissions:
            # Give the default GITHUB_TOKEN write permission
            contents: write
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: '3.9' 
            - run: |
                pip3 install pyinstaller==5.13.2
            - run: |
                pyinstaller -F src/main.py
                rm main.spec
                rm -rf build
                cp -r src/ tkbBooking
                mv dist/main tkbBooking/tkbBooking
                rm -rf dist

            - uses: peter-evans/create-pull-request@v5
              with:
                title: 'build: auto-packing the executable'
                commit-message: 'build: auto-packing the executable'
                delete-branch: true
            - uses: pascalgn/automerge-action@v0.15.6
              env:
                GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
            

